# Generated for CMake MVP (no V8 / no XFA / AGG). Do not hand-edit.
# Regenerate: python tools/gen_cmake_sources.py

# third_party fx_agg
set(PDFIUM_AGG_SOURCES
  third_party/agg23/agg_curves.cpp
  third_party/agg23/agg_path_storage.cpp
  third_party/agg23/agg_rasterizer_scanline_aa.cpp
  third_party/agg23/agg_vcgen_dash.cpp
  third_party/agg23/agg_vcgen_stroke.cpp
)

# third_party fx_lcms2
set(PDFIUM_LCMS_SOURCES
  third_party/lcms/src/cmsalpha.c
  third_party/lcms/src/cmscam02.c
  third_party/lcms/src/cmscgats.c
  third_party/lcms/src/cmscnvrt.c
  third_party/lcms/src/cmserr.c
  third_party/lcms/src/cmsgamma.c
  third_party/lcms/src/cmsgmt.c
  third_party/lcms/src/cmshalf.c
  third_party/lcms/src/cmsintrp.c
  third_party/lcms/src/cmsio0.c
  third_party/lcms/src/cmsio1.c
  third_party/lcms/src/cmslut.c
  third_party/lcms/src/cmsmd5.c
  third_party/lcms/src/cmsmtrx.c
  third_party/lcms/src/cmsnamed.c
  third_party/lcms/src/cmsopt.c
  third_party/lcms/src/cmspack.c
  third_party/lcms/src/cmspcs.c
  third_party/lcms/src/cmsplugin.c
  third_party/lcms/src/cmsps2.c
  third_party/lcms/src/cmssamp.c
  third_party/lcms/src/cmssm.c
  third_party/lcms/src/cmstypes.c
  third_party/lcms/src/cmsvirt.c
  third_party/lcms/src/cmswtpnt.c
  third_party/lcms/src/cmsxform.c
)

# third_party fx_libopenjpeg
set(PDFIUM_OPENJPEG_SOURCES
  third_party/libopenjpeg/bio.c
  third_party/libopenjpeg/cio.c
  third_party/libopenjpeg/dwt.c
  third_party/libopenjpeg/event.c
  third_party/libopenjpeg/function_list.c
  third_party/libopenjpeg/ht_dec.c
  third_party/libopenjpeg/image.c
  third_party/libopenjpeg/invert.c
  third_party/libopenjpeg/j2k.c
  third_party/libopenjpeg/jp2.c
  third_party/libopenjpeg/mct.c
  third_party/libopenjpeg/mqc.c
  third_party/libopenjpeg/openjpeg.c
  third_party/libopenjpeg/opj_malloc.cc
  third_party/libopenjpeg/pi.c
  third_party/libopenjpeg/sparse_array.c
  third_party/libopenjpeg/t1.c
  third_party/libopenjpeg/t2.c
  third_party/libopenjpeg/tcd.c
  third_party/libopenjpeg/tgt.c
  third_party/libopenjpeg/thread.c
)

# core/fxcrt common
set(PDFIUM_FXCRT_SOURCES
  core/fxcrt/binary_buffer.cpp
  core/fxcrt/bytestring.cpp
  core/fxcrt/bytestring_pool.cpp
  core/fxcrt/cfx_bitstream.cpp
  core/fxcrt/cfx_datetime.cpp
  core/fxcrt/cfx_fileaccess_stream.cpp
  core/fxcrt/cfx_read_only_container_stream.cpp
  core/fxcrt/cfx_read_only_span_stream.cpp
  core/fxcrt/cfx_seekablestreamproxy.cpp
  core/fxcrt/cfx_timer.cpp
  core/fxcrt/debug/alias.cc
  core/fxcrt/fx_bidi.cpp
  core/fxcrt/fx_codepage.cpp
  core/fxcrt/fx_coordinates.cpp
  core/fxcrt/fx_extension.cpp
  core/fxcrt/fx_memory.cpp
  core/fxcrt/fx_memory_malloc.cpp
  core/fxcrt/fx_number.cpp
  core/fxcrt/fx_random.cpp
  core/fxcrt/fx_stream.cpp
  core/fxcrt/fx_string.cpp
  core/fxcrt/fx_system.cpp
  core/fxcrt/fx_unicode.cpp
  core/fxcrt/observed_ptr.cpp
  core/fxcrt/string_data_template.cpp
  core/fxcrt/string_template.cpp
  core/fxcrt/widestring.cpp
  core/fxcrt/widetext_buffer.cpp
  core/fxcrt/xml/cfx_xmlchardata.cpp
  core/fxcrt/xml/cfx_xmldocument.cpp
  core/fxcrt/xml/cfx_xmlelement.cpp
  core/fxcrt/xml/cfx_xmlinstruction.cpp
  core/fxcrt/xml/cfx_xmlnode.cpp
  core/fxcrt/xml/cfx_xmlparser.cpp
  core/fxcrt/xml/cfx_xmltext.cpp
)

# core/fxcrt posix
set(PDFIUM_FXCRT_POSIX_SOURCES
  core/fxcrt/cfx_fileaccess_posix.cpp
  core/fxcrt/fx_folder_posix.cpp
  core/fxcrt/mapped_data_bytes.cpp
)

# core/fxcrt win
set(PDFIUM_FXCRT_WIN_SOURCES
  core/fxcrt/cfx_fileaccess_windows.cpp
  core/fxcrt/code_point_view.cpp
  core/fxcrt/fx_folder_windows.cpp
  core/fxcrt/win/win_util.cc
)

# core/fxcodec
set(PDFIUM_FXCODEC_SOURCES
  core/fxcodec/basic/basicmodule.cpp
  core/fxcodec/data_and_bytes_consumed.cpp
  core/fxcodec/fax/faxmodule.cpp
  core/fxcodec/flate/flatemodule.cpp
  core/fxcodec/fx_codec.cpp
  core/fxcodec/icc/icc_transform.cpp
  core/fxcodec/jpeg/jpeg_common.c
  core/fxcodec/jpeg/jpegmodule.cpp
  core/fxcodec/jpx/cjpx_decoder.cpp
  core/fxcodec/jpx/jpx_decode_utils.cpp
  core/fxcodec/scanlinedecoder.cpp
  core/fxcodec/jbig2/jbig2_arith_decoder.cpp
  core/fxcodec/jbig2/jbig2_arith_int_decoder.cpp
  core/fxcodec/jbig2/jbig2_bit_stream.cpp
  core/fxcodec/jbig2/jbig2_context.cpp
  core/fxcodec/jbig2/jbig2_decoder.cpp
  core/fxcodec/jbig2/jbig2_document_context.cpp
  core/fxcodec/jbig2/jbig2_grd_proc.cpp
  core/fxcodec/jbig2/jbig2_grrd_proc.cpp
  core/fxcodec/jbig2/jbig2_htrd_proc.cpp
  core/fxcodec/jbig2/jbig2_huffman_decoder.cpp
  core/fxcodec/jbig2/jbig2_huffman_table.cpp
  core/fxcodec/jbig2/jbig2_image.cpp
  core/fxcodec/jbig2/jbig2_pattern_dict.cpp
  core/fxcodec/jbig2/jbig2_pdd_proc.cpp
  core/fxcodec/jbig2/jbig2_sdd_proc.cpp
  core/fxcodec/jbig2/jbig2_segment.cpp
  core/fxcodec/jbig2/jbig2_symbol_dict.cpp
  core/fxcodec/jbig2/jbig2_trd_proc.cpp
)

# core/fxge + AGG
set(PDFIUM_FXGE_SOURCES
  core/fxge/calculate_pitch.cpp
  core/fxge/cfx_charmap_resolver.cpp
  core/fxge/cfx_color.cpp
  core/fxge/cfx_cttgsubtable.cpp
  core/fxge/cfx_drawutils.cpp
  core/fxge/cfx_face.cpp
  core/fxge/cfx_folderfontinfo.cpp
  core/fxge/cfx_font.cpp
  core/fxge/cfx_fontmapper.cpp
  core/fxge/cfx_fontmgr.cpp
  core/fxge/cfx_gemodule.cpp
  core/fxge/cfx_glyphbitmap.cpp
  core/fxge/cfx_glyphcache.cpp
  core/fxge/cfx_graphstate.cpp
  core/fxge/cfx_graphstatedata.cpp
  core/fxge/cfx_path.cpp
  core/fxge/cfx_renderdevice.cpp
  core/fxge/cfx_standardfont.cpp
  core/fxge/cfx_substfont.cpp
  core/fxge/dib/blend.cpp
  core/fxge/dib/cfx_bitmapstorer.cpp
  core/fxge/dib/cfx_cmyk_to_srgb.cpp
  core/fxge/dib/cfx_dibbase.cpp
  core/fxge/dib/cfx_dibitmap.cpp
  core/fxge/dib/cfx_imagestretcher.cpp
  core/fxge/dib/cfx_imagetransformer.cpp
  core/fxge/dib/cfx_scanlinecompositor.cpp
  core/fxge/dib/cstretchengine.cpp
  core/fxge/dib/fx_dib.cpp
  core/fxge/freetype/fx_freetype.cpp
  core/fxge/fx_font.cpp
  core/fxge/renderdevicedriver_iface.cpp
  core/fxge/text_char_pos.cpp
  core/fxge/text_glyph_pos.cpp
  core/fxge/agg/cfx_agg_bitmapcomposer.cpp
  core/fxge/agg/cfx_agg_cliprgn.cpp
  core/fxge/agg/cfx_agg_devicedriver.cpp
  core/fxge/agg/cfx_agg_imagerenderer.cpp
  core/fxge/fontdata/chromefontdata/FoxitDingbats.cpp
  core/fxge/fontdata/chromefontdata/FoxitFixed.cpp
  core/fxge/fontdata/chromefontdata/FoxitFixedBold.cpp
  core/fxge/fontdata/chromefontdata/FoxitFixedBoldItalic.cpp
  core/fxge/fontdata/chromefontdata/FoxitFixedItalic.cpp
  core/fxge/fontdata/chromefontdata/FoxitSans.cpp
  core/fxge/fontdata/chromefontdata/FoxitSansBold.cpp
  core/fxge/fontdata/chromefontdata/FoxitSansBoldItalic.cpp
  core/fxge/fontdata/chromefontdata/FoxitSansItalic.cpp
  core/fxge/fontdata/chromefontdata/FoxitSansMM.cpp
  core/fxge/fontdata/chromefontdata/FoxitSerif.cpp
  core/fxge/fontdata/chromefontdata/FoxitSerifBold.cpp
  core/fxge/fontdata/chromefontdata/FoxitSerifBoldItalic.cpp
  core/fxge/fontdata/chromefontdata/FoxitSerifItalic.cpp
  core/fxge/fontdata/chromefontdata/FoxitSerifMM.cpp
  core/fxge/fontdata/chromefontdata/FoxitSymbol.cpp
)

# fxge linux
set(PDFIUM_FXGE_LINUX_SOURCES
  core/fxge/linux/fx_linux_impl.cpp
)

# fxge mac
set(PDFIUM_FXGE_MAC_SOURCES
  core/fxge/apple/capple_platform.cpp
  core/fxge/apple/cquartz_2d.cpp
  core/fxge/apple/fx_apple_impl.cpp
)

# fxge win
set(PDFIUM_FXGE_WIN_SOURCES
  core/fxge/win32/cfx_psfonttracker.cpp
  core/fxge/win32/cfx_psrenderer.cpp
  core/fxge/win32/cgdi_device_driver.cpp
  core/fxge/win32/cgdi_display_driver.cpp
  core/fxge/win32/cgdi_plus_ext.cpp
  core/fxge/win32/cgdi_printer_driver.cpp
  core/fxge/win32/cps_printer_driver.cpp
  core/fxge/win32/cpsoutput.cpp
  core/fxge/win32/ctext_only_printer_driver.cpp
  core/fxge/win32/cwin32_platform.cpp
)

# fdrm
set(PDFIUM_FDRM_SOURCES
  core/fdrm/fx_crypt.cpp
  core/fdrm/fx_crypt_aes.cpp
  core/fdrm/fx_crypt_sha.cpp
)

# fpdfapi/cmaps
set(PDFIUM_CMAPS_SOURCES
  core/fpdfapi/cmaps/CNS1/B5pc-H_0.cpp
  core/fpdfapi/cmaps/CNS1/B5pc-V_0.cpp
  core/fpdfapi/cmaps/CNS1/CNS-EUC-H_0.cpp
  core/fpdfapi/cmaps/CNS1/CNS-EUC-V_0.cpp
  core/fpdfapi/cmaps/CNS1/ETen-B5-H_0.cpp
  core/fpdfapi/cmaps/CNS1/ETen-B5-V_0.cpp
  core/fpdfapi/cmaps/CNS1/ETenms-B5-H_0.cpp
  core/fpdfapi/cmaps/CNS1/ETenms-B5-V_0.cpp
  core/fpdfapi/cmaps/CNS1/HKscs-B5-H_5.cpp
  core/fpdfapi/cmaps/CNS1/HKscs-B5-V_5.cpp
  core/fpdfapi/cmaps/CNS1/UniCNS-UCS2-H_3.cpp
  core/fpdfapi/cmaps/CNS1/UniCNS-UCS2-V_3.cpp
  core/fpdfapi/cmaps/CNS1/UniCNS-UTF16-H_0.cpp
  core/fpdfapi/cmaps/fpdf_cmaps.cpp
  core/fpdfapi/cmaps/GB1/GB-EUC-H_0.cpp
  core/fpdfapi/cmaps/GB1/GB-EUC-V_0.cpp
  core/fpdfapi/cmaps/GB1/GBK-EUC-H_2.cpp
  core/fpdfapi/cmaps/GB1/GBK-EUC-V_2.cpp
  core/fpdfapi/cmaps/GB1/GBK2K-H_5.cpp
  core/fpdfapi/cmaps/GB1/GBK2K-V_5.cpp
  core/fpdfapi/cmaps/GB1/GBKp-EUC-H_2.cpp
  core/fpdfapi/cmaps/GB1/GBKp-EUC-V_2.cpp
  core/fpdfapi/cmaps/GB1/GBpc-EUC-H_0.cpp
  core/fpdfapi/cmaps/GB1/GBpc-EUC-V_0.cpp
  core/fpdfapi/cmaps/GB1/UniGB-UCS2-H_4.cpp
  core/fpdfapi/cmaps/GB1/UniGB-UCS2-V_4.cpp
  core/fpdfapi/cmaps/Japan1/83pv-RKSJ-H_1.cpp
  core/fpdfapi/cmaps/Japan1/90ms-RKSJ-H_2.cpp
  core/fpdfapi/cmaps/Japan1/90ms-RKSJ-V_2.cpp
  core/fpdfapi/cmaps/Japan1/90msp-RKSJ-H_2.cpp
  core/fpdfapi/cmaps/Japan1/90msp-RKSJ-V_2.cpp
  core/fpdfapi/cmaps/Japan1/90pv-RKSJ-H_1.cpp
  core/fpdfapi/cmaps/Japan1/Add-RKSJ-H_1.cpp
  core/fpdfapi/cmaps/Japan1/Add-RKSJ-V_1.cpp
  core/fpdfapi/cmaps/Japan1/EUC-H_1.cpp
  core/fpdfapi/cmaps/Japan1/EUC-V_1.cpp
  core/fpdfapi/cmaps/Japan1/Ext-RKSJ-H_2.cpp
  core/fpdfapi/cmaps/Japan1/Ext-RKSJ-V_2.cpp
  core/fpdfapi/cmaps/Japan1/H_1.cpp
  core/fpdfapi/cmaps/Japan1/UniJIS-UCS2-H_4.cpp
  core/fpdfapi/cmaps/Japan1/UniJIS-UCS2-HW-H_4.cpp
  core/fpdfapi/cmaps/Japan1/UniJIS-UCS2-HW-V_4.cpp
  core/fpdfapi/cmaps/Japan1/UniJIS-UCS2-V_4.cpp
  core/fpdfapi/cmaps/Japan1/V_1.cpp
  core/fpdfapi/cmaps/Korea1/KSC-EUC-H_0.cpp
  core/fpdfapi/cmaps/Korea1/KSC-EUC-V_0.cpp
  core/fpdfapi/cmaps/Korea1/KSCms-UHC-H_1.cpp
  core/fpdfapi/cmaps/Korea1/KSCms-UHC-HW-H_1.cpp
  core/fpdfapi/cmaps/Korea1/KSCms-UHC-HW-V_1.cpp
  core/fpdfapi/cmaps/Korea1/KSCms-UHC-V_1.cpp
  core/fpdfapi/cmaps/Korea1/KSCpc-EUC-H_0.cpp
  core/fpdfapi/cmaps/Korea1/UniKS-UCS2-H_1.cpp
  core/fpdfapi/cmaps/Korea1/UniKS-UCS2-V_1.cpp
  core/fpdfapi/cmaps/Korea1/UniKS-UTF16-H_0.cpp
)

# fpdfapi/font
set(PDFIUM_FONT_SOURCES
  core/fpdfapi/font/cpdf_cid2unicodemap.cpp
  core/fpdfapi/font/cpdf_cidfont.cpp
  core/fpdfapi/font/cpdf_cmap.cpp
  core/fpdfapi/font/cpdf_cmapparser.cpp
  core/fpdfapi/font/cpdf_facebasedsimplefont.cpp
  core/fpdfapi/font/cpdf_font.cpp
  core/fpdfapi/font/cpdf_fontencoding.cpp
  core/fpdfapi/font/cpdf_fontglobals.cpp
  core/fpdfapi/font/cpdf_simplefont.cpp
  core/fpdfapi/font/cpdf_stockfontarray.cpp
  core/fpdfapi/font/cpdf_tounicodemap.cpp
  core/fpdfapi/font/cpdf_truetypefont.cpp
  core/fpdfapi/font/cpdf_type1font.cpp
  core/fpdfapi/font/cpdf_type3char.cpp
  core/fpdfapi/font/cpdf_type3font.cpp
)

# fpdfapi/page
set(PDFIUM_PAGE_SOURCES
  core/fpdfapi/page/cpdf_allstates.cpp
  core/fpdfapi/page/cpdf_annotcontext.cpp
  core/fpdfapi/page/cpdf_basedcs.cpp
  core/fpdfapi/page/cpdf_clippath.cpp
  core/fpdfapi/page/cpdf_color.cpp
  core/fpdfapi/page/cpdf_colorspace.cpp
  core/fpdfapi/page/cpdf_colorstate.cpp
  core/fpdfapi/page/cpdf_contentmarkitem.cpp
  core/fpdfapi/page/cpdf_contentmarks.cpp
  core/fpdfapi/page/cpdf_contentparser.cpp
  core/fpdfapi/page/cpdf_devicecs.cpp
  core/fpdfapi/page/cpdf_dib.cpp
  core/fpdfapi/page/cpdf_docpagedata.cpp
  core/fpdfapi/page/cpdf_expintfunc.cpp
  core/fpdfapi/page/cpdf_form.cpp
  core/fpdfapi/page/cpdf_formobject.cpp
  core/fpdfapi/page/cpdf_function.cpp
  core/fpdfapi/page/cpdf_generalstate.cpp
  core/fpdfapi/page/cpdf_graphicstates.cpp
  core/fpdfapi/page/cpdf_iccprofile.cpp
  core/fpdfapi/page/cpdf_image.cpp
  core/fpdfapi/page/cpdf_imageloader.cpp
  core/fpdfapi/page/cpdf_imageobject.cpp
  core/fpdfapi/page/cpdf_indexedcs.cpp
  core/fpdfapi/page/cpdf_meshstream.cpp
  core/fpdfapi/page/cpdf_occontext.cpp
  core/fpdfapi/page/cpdf_page.cpp
  core/fpdfapi/page/cpdf_pageimagecache.cpp
  core/fpdfapi/page/cpdf_pagemodule.cpp
  core/fpdfapi/page/cpdf_pageobject.cpp
  core/fpdfapi/page/cpdf_pageobjectholder.cpp
  core/fpdfapi/page/cpdf_path.cpp
  core/fpdfapi/page/cpdf_pathobject.cpp
  core/fpdfapi/page/cpdf_pattern.cpp
  core/fpdfapi/page/cpdf_patterncs.cpp
  core/fpdfapi/page/cpdf_psengine.cpp
  core/fpdfapi/page/cpdf_psfunc.cpp
  core/fpdfapi/page/cpdf_sampledfunc.cpp
  core/fpdfapi/page/cpdf_shadingobject.cpp
  core/fpdfapi/page/cpdf_shadingpattern.cpp
  core/fpdfapi/page/cpdf_stitchfunc.cpp
  core/fpdfapi/page/cpdf_streamcontentparser.cpp
  core/fpdfapi/page/cpdf_streamparser.cpp
  core/fpdfapi/page/cpdf_textobject.cpp
  core/fpdfapi/page/cpdf_textstate.cpp
  core/fpdfapi/page/cpdf_tilingpattern.cpp
  core/fpdfapi/page/cpdf_transferfunc.cpp
  core/fpdfapi/page/cpdf_transferfuncdib.cpp
  core/fpdfapi/page/cpdf_transparency.cpp
  core/fpdfapi/page/jpx_decode_conversion.cpp
)

# fpdfapi/parser
set(PDFIUM_PARSER_SOURCES
  core/fpdfapi/parser/cfdf_document.cpp
  core/fpdfapi/parser/cpdf_array.cpp
  core/fpdfapi/parser/cpdf_boolean.cpp
  core/fpdfapi/parser/cpdf_cross_ref_avail.cpp
  core/fpdfapi/parser/cpdf_cross_ref_table.cpp
  core/fpdfapi/parser/cpdf_crypto_handler.cpp
  core/fpdfapi/parser/cpdf_data_avail.cpp
  core/fpdfapi/parser/cpdf_dictionary.cpp
  core/fpdfapi/parser/cpdf_document.cpp
  core/fpdfapi/parser/cpdf_encryptor.cpp
  core/fpdfapi/parser/cpdf_flateencoder.cpp
  core/fpdfapi/parser/cpdf_hint_tables.cpp
  core/fpdfapi/parser/cpdf_indirect_object_holder.cpp
  core/fpdfapi/parser/cpdf_linearized_header.cpp
  core/fpdfapi/parser/cpdf_name.cpp
  core/fpdfapi/parser/cpdf_null.cpp
  core/fpdfapi/parser/cpdf_number.cpp
  core/fpdfapi/parser/cpdf_object.cpp
  core/fpdfapi/parser/cpdf_object_avail.cpp
  core/fpdfapi/parser/cpdf_object_stream.cpp
  core/fpdfapi/parser/cpdf_object_walker.cpp
  core/fpdfapi/parser/cpdf_page_object_avail.cpp
  core/fpdfapi/parser/cpdf_parser.cpp
  core/fpdfapi/parser/cpdf_read_validator.cpp
  core/fpdfapi/parser/cpdf_reference.cpp
  core/fpdfapi/parser/cpdf_security_handler.cpp
  core/fpdfapi/parser/cpdf_simple_parser.cpp
  core/fpdfapi/parser/cpdf_stream.cpp
  core/fpdfapi/parser/cpdf_stream_acc.cpp
  core/fpdfapi/parser/cpdf_string.cpp
  core/fpdfapi/parser/cpdf_syntax_parser.cpp
  core/fpdfapi/parser/fpdf_parser_decode.cpp
  core/fpdfapi/parser/fpdf_parser_utility.cpp
  core/fpdfapi/parser/object_tree_traversal_util.cpp
)

# fpdfapi/render
set(PDFIUM_RENDER_SOURCES
  core/fpdfapi/render/cpdf_devicebuffer.cpp
  core/fpdfapi/render/cpdf_docrenderdata.cpp
  core/fpdfapi/render/cpdf_imagerenderer.cpp
  core/fpdfapi/render/cpdf_pagerendercontext.cpp
  core/fpdfapi/render/cpdf_progressiverenderer.cpp
  core/fpdfapi/render/cpdf_rendercontext.cpp
  core/fpdfapi/render/cpdf_renderoptions.cpp
  core/fpdfapi/render/cpdf_rendershading.cpp
  core/fpdfapi/render/cpdf_renderstatus.cpp
  core/fpdfapi/render/cpdf_rendertiling.cpp
  core/fpdfapi/render/cpdf_textrenderer.cpp
  core/fpdfapi/render/cpdf_type3cache.cpp
  core/fpdfapi/render/cpdf_type3glyphmap.cpp
)

# fpdfapi/render win
set(PDFIUM_RENDER_WIN_SOURCES
  core/fpdfapi/render/cpdf_scaledrenderbuffer.cpp
)

# fpdfapi/edit
set(PDFIUM_EDIT_SOURCES
  core/fpdfapi/edit/cpdf_contentstream_write_utils.cpp
  core/fpdfapi/edit/cpdf_creator.cpp
  core/fpdfapi/edit/cpdf_font_util.cpp
  core/fpdfapi/edit/cpdf_fontsubsetter.cpp
  core/fpdfapi/edit/cpdf_npagetooneexporter.cpp
  core/fpdfapi/edit/cpdf_pagecontentgenerator.cpp
  core/fpdfapi/edit/cpdf_pagecontentmanager.cpp
  core/fpdfapi/edit/cpdf_pageexporter.cpp
  core/fpdfapi/edit/cpdf_pageorganizer.cpp
  core/fpdfapi/edit/cpdf_stringarchivestream.cpp
)

# fpdfdoc
set(PDFIUM_FPDFDOC_SOURCES
  core/fpdfdoc/cpdf_aaction.cpp
  core/fpdfdoc/cpdf_action.cpp
  core/fpdfdoc/cpdf_annot.cpp
  core/fpdfdoc/cpdf_annotlist.cpp
  core/fpdfdoc/cpdf_apsettings.cpp
  core/fpdfdoc/cpdf_bafontmap.cpp
  core/fpdfdoc/cpdf_bookmark.cpp
  core/fpdfdoc/cpdf_bookmarktree.cpp
  core/fpdfdoc/cpdf_color_utils.cpp
  core/fpdfdoc/cpdf_defaultappearance.cpp
  core/fpdfdoc/cpdf_dest.cpp
  core/fpdfdoc/cpdf_filespec.cpp
  core/fpdfdoc/cpdf_formcontrol.cpp
  core/fpdfdoc/cpdf_formfield.cpp
  core/fpdfdoc/cpdf_generateap.cpp
  core/fpdfdoc/cpdf_icon.cpp
  core/fpdfdoc/cpdf_iconfit.cpp
  core/fpdfdoc/cpdf_interactiveform.cpp
  core/fpdfdoc/cpdf_link.cpp
  core/fpdfdoc/cpdf_linklist.cpp
  core/fpdfdoc/cpdf_metadata.cpp
  core/fpdfdoc/cpdf_nametree.cpp
  core/fpdfdoc/cpdf_numbertree.cpp
  core/fpdfdoc/cpdf_pagelabel.cpp
  core/fpdfdoc/cpdf_structelement.cpp
  core/fpdfdoc/cpdf_structtree.cpp
  core/fpdfdoc/cpdf_viewerpreferences.cpp
  core/fpdfdoc/cpvt_fontmap.cpp
  core/fpdfdoc/cpvt_section.cpp
  core/fpdfdoc/cpvt_stub_provider.cpp
  core/fpdfdoc/cpvt_variabletext.cpp
  core/fpdfdoc/cpvt_word.cpp
  core/fpdfdoc/cpvt_wordinfo.cpp
)

# fpdftext
set(PDFIUM_FPDFTEXT_SOURCES
  core/fpdftext/cpdf_linkextract.cpp
  core/fpdftext/cpdf_textpage.cpp
  core/fpdftext/cpdf_textpagefind.cpp
  core/fpdftext/unicodenormalizationdata.cpp
)

# fpdfsdk
set(PDFIUM_FPDFSDK_SOURCES
  fpdfsdk/cpdfsdk_annot.cpp
  fpdfsdk/cpdfsdk_annotiteration.cpp
  fpdfsdk/cpdfsdk_annotiterator.cpp
  fpdfsdk/cpdfsdk_appstream.cpp
  fpdfsdk/cpdfsdk_baannot.cpp
  fpdfsdk/cpdfsdk_customaccess.cpp
  fpdfsdk/cpdfsdk_filewriteadapter.cpp
  fpdfsdk/cpdfsdk_formfillenvironment.cpp
  fpdfsdk/cpdfsdk_helpers.cpp
  fpdfsdk/cpdfsdk_interactiveform.cpp
  fpdfsdk/cpdfsdk_pageview.cpp
  fpdfsdk/cpdfsdk_pauseadapter.cpp
  fpdfsdk/cpdfsdk_renderpage.cpp
  fpdfsdk/cpdfsdk_widget.cpp
  fpdfsdk/fpdf_annot.cpp
  fpdfsdk/fpdf_attachment.cpp
  fpdfsdk/fpdf_catalog.cpp
  fpdfsdk/fpdf_dataavail.cpp
  fpdfsdk/fpdf_doc.cpp
  fpdfsdk/fpdf_editimg.cpp
  fpdfsdk/fpdf_editpage.cpp
  fpdfsdk/fpdf_editpath.cpp
  fpdfsdk/fpdf_edittext.cpp
  fpdfsdk/fpdf_ext.cpp
  fpdfsdk/fpdf_flatten.cpp
  fpdfsdk/fpdf_formfill.cpp
  fpdfsdk/fpdf_javascript.cpp
  fpdfsdk/fpdf_ppo.cpp
  fpdfsdk/fpdf_progressive.cpp
  fpdfsdk/fpdf_save.cpp
  fpdfsdk/fpdf_searchex.cpp
  fpdfsdk/fpdf_signature.cpp
  fpdfsdk/fpdf_structtree.cpp
  fpdfsdk/fpdf_sysfontinfo.cpp
  fpdfsdk/fpdf_text.cpp
  fpdfsdk/fpdf_thumbnail.cpp
  fpdfsdk/fpdf_transformpage.cpp
  fpdfsdk/fpdf_view.cpp
)

# formfiller
set(PDFIUM_FORMFILLER_SOURCES
  fpdfsdk/formfiller/cffl_button.cpp
  fpdfsdk/formfiller/cffl_checkbox.cpp
  fpdfsdk/formfiller/cffl_combobox.cpp
  fpdfsdk/formfiller/cffl_fieldaction.cpp
  fpdfsdk/formfiller/cffl_formfield.cpp
  fpdfsdk/formfiller/cffl_interactiveformfiller.cpp
  fpdfsdk/formfiller/cffl_listbox.cpp
  fpdfsdk/formfiller/cffl_perwindowdata.cpp
  fpdfsdk/formfiller/cffl_pushbutton.cpp
  fpdfsdk/formfiller/cffl_radiobutton.cpp
  fpdfsdk/formfiller/cffl_textfield.cpp
  fpdfsdk/formfiller/cffl_textobject.cpp
)

# pwl
set(PDFIUM_PWL_SOURCES
  fpdfsdk/pwl/cpwl_button.cpp
  fpdfsdk/pwl/cpwl_caret.cpp
  fpdfsdk/pwl/cpwl_cbbutton.cpp
  fpdfsdk/pwl/cpwl_cblistbox.cpp
  fpdfsdk/pwl/cpwl_combo_box.cpp
  fpdfsdk/pwl/cpwl_edit.cpp
  fpdfsdk/pwl/cpwl_edit_impl.cpp
  fpdfsdk/pwl/cpwl_list_box.cpp
  fpdfsdk/pwl/cpwl_list_ctrl.cpp
  fpdfsdk/pwl/cpwl_sbbutton.cpp
  fpdfsdk/pwl/cpwl_scroll_bar.cpp
  fpdfsdk/pwl/cpwl_special_button.cpp
  fpdfsdk/pwl/cpwl_wnd.cpp
)

# fxjs stubs
set(PDFIUM_FXJS_STUB_SOURCES
  fxjs/cjs_event_context_stub.cpp
  fxjs/cjs_runtimestub.cpp
  fxjs/ijs_runtime.cpp
)

